# Generated by Django 4.2 on 2023-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emailaddress', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'visitydata',
                'managed': False,
            },
        ),
    ]
